apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m6xl3dupv-python 
  janus-idp.io/tekton: m6xl3dupv-python
  backstage.io/kubernetes-id: m6xl3dupv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m6xl3dupv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml