apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m6xl3dupv-python
  janus-idp.io/tekton: m6xl3dupv-python
  backstage.io/kubernetes-id: m6xl3dupv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m6xl3dupv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
